apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-jars-pvc
  namespace: zeatarou
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: storageClassName