apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: example-spark-job
spec:
  type: Python
  mode: cluster
  image: "spark:3.5.3"
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark/work-dir/example_job.py"
  sparkVersion: "3.5.3"
  restartPolicy:
    type: Never
  volumes:
    - name: example-job-volume
      configMap:
        name: example-job-py
  driver:
    cores: 1
    memory: "1G"
    labels:
      version: 3.5.3
    serviceAccount: zeatarou-spark-operator-spark # ServiceAccount in the same namespace as the Spark Operator
    volumeMounts:
      - name: example-job-volume
        mountPath: /opt/spark/work-dir
  executor:
    cores: 1
    instances: 2
    memory: "1G"
    labels:
      version: 3.5.3
    volumeMounts:
      - name: example-job-volume
        mountPath: /opt/spark/work-dir